# 图像路径配置
template_path: 'source/1.2/template2.jpg'

precision: 2              # 显示精度（小数点后位数）
unit: 'MPa'               # 单位

# 模板刻度点集标注
candidate_points:
  - [700, 766] # 刻度点1
  - [624, 659] # 刻度点2
  - [603, 528] # 刻度点3
  - [647, 403] # 刻度点4
  - [745, 311] # 刻度点5
  - [851, 276] # 刻度点6
  - [981, 292] # 刻度点7
  - [1086, 361] # 刻度点8
  - [1152, 472] # 刻度点9
  - [1160, 601] # 刻度点10
  - [1107, 720] # 刻度点11
candidate_points_value: [-0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
# 扫描区域设置

scan_zone:
  center_point: [977,355] # 指针上的一点 作为环形扫描区域的中线点
  radius: 30                # 扫描区域半径
  angle: 5                # 扫描区域扇形角度

