# 图像路径配置
image:
  path: 'source/1.1/template2.jpg'

# 模板刻度点集标注
# 这些点用于表盘刻度区域的识别
candidate_points:
  - [700, 766] # 刻度点1
  - [624, 659] # 刻度点2
  - [603, 528] # 刻度点3
  - [647, 403] # 刻度点4
  - [745, 311] # 刻度点5
  - [851, 276] # 刻度点6
  - [981, 292] # 刻度点7
  - [1086, 361] # 刻度点8
  - [1152, 472] # 刻度点9
  - [1160, 601] # 刻度点10
  - [1107, 720] # 刻度点11

# 扫描区域设置
scan_zone:
  center_point: [970,362] # 指针上的一点 作为环形扫描区域的中线点
  radius: 20                # 扫描区域半径
  angle: 10                # 扫描区域扇形角度
  valid_threshold: 70       # 要求扇形区域至少包含了valid_threshold个像素点才能被统计

# 表盘刻度设置
scale:
  step: 5              # 标注刻度之间未标注的刻度数量（估读刻度默认10）
  start: -0.1               # 起始刻度值
  end: 0.9                  # 终止刻度值
  precision: 2              # 显示精度（小数点后位数）
  unit: 'MPa'               # 单位