# 图像路径配置
template_path: 'source/1.3/template.jpg'
precision: 2              # 显示精度（小数点后位数）
unit: 'MPa'               # 单位
# 模板刻度点集标注
candidate_points:
  - [138, 578] # 刻度点1
  - [77, 441] # 刻度点1
  - [86, 292] # 刻度点2
  - [161, 167] # 刻度点2
  - [284, 88] # 刻度点3
  - [427, 72] # 刻度点3
  - [561, 121] # 刻度点4
  - [659, 224] # 刻度点4
  - [701, 360] # 刻度点5
  - [675, 502] # 刻度点5
  - [588, 620] # 刻度点6
candidate_points_value: [0.0, 2.5, 5, 7.5, 10, 12.5, 15, 17.5, 20, 22.5, 25]
# 扫描区域设置
scan_zone:
  center_point: [ 264, 305 ] # 指针上的一点 作为环形扫描区域的中线点
  radius: 145                # 扫描区域半径
  width: 15                # 指针宽度（方便进行扫描）

