# 图像路径配置
template_path: 'source/2.1/template.jpg'
precision: 0              # 显示精度（小数点后位数）
unit: 'mA'               # 单位
# 模板刻度点集标注
candidate_points:
  - [602, 774] # 刻度点1
  - [596, 768] # 刻度点2
  - [557, 638] # 刻度点3
  - [622, 484] # 刻度点4
  - [777, 424] # 刻度点5
  - [930, 489] # 刻度点6
  - [992, 644] # 刻度点6
  - [927, 799] # 刻度点6
candidate_points_value: [0, 2, 10, 20, 30, 40, 50, 60]
# 扫描区域设置
scan_zone:
  center_point: [609, 621] # 指针上的一点 作为环形扫描区域的中线点
  radius: 40                # 扫描区域半径
  width: 3                # 指针宽度（方便进行扫描）
  pointer_num: 2        # 指针数量