# 图像路径配置
template_path: 'source/1.5/template.png'
precision: 1              # 显示精度（小数点后位数）
unit: 'mA'               # 单位
# 模板刻度点集标注
candidate_points:
  - [68, 173] # 刻度点1
  - [60, 141] # 刻度点2
  - [64, 100] # 刻度点3
  - [89, 63] # 刻度点4
  - [128, 44] # 刻度点5
  - [172, 44] # 刻度点6
  - [210, 63]
  - [235, 95]
  - [243, 135]
  - [231, 178]
candidate_points_value: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
# 扫描区域设置
scan_zone:
  center_point: [191, 109] # 指针上的一点 作为环形扫描区域的中线点
  radius: 16                # 扫描区域半径
  width: 15                # 指针宽度（方便进行扫描）