# 图像路径配置
image:
  path: 'source/1.5/template.png'

# 模板刻度点集标注
# 这些点用于表盘刻度区域的识别
candidate_points:
   - [60, 177] # 刻度点1	
   - [50, 142]
   - [66, 75]
   - [136, 32]
   - [205, 48]
   - [226, 66]
   - [252, 127]
   - [239, 184]
   
   
 # - [69, 173] # 刻度点1
 # - [64, 101] # 刻度点1
 # - [151, 42] # 刻度点2
 # - [235, 95] # 刻度点1
 # - [231, 179] # 刻度点2


# 扫描区域设置
scan_zone:
  center_point: [190,112] # 指针上的一点 作为环形扫描区域的中线点
  radius: 20                # 扫描区域半径
  angle: 15                 # 扫描区域扇形角度
  valid_threshold: 70       # 要求扇形区域至少包含了valid_threshold个像素点才能被统计

# 表盘刻度设置
scale:
  step: 5              # 标注刻度之间未标注的刻度数量（估读刻度默认10）
  start: 9              # 起始刻度值
  end: 25                  # 终止刻度值
  precision: 2              # 显示精度（小数点后位数）
  unit: 'MPa'               # 单位
