# 图像路径配置
template_path: 'source/1.7/template.png'
precision: 0              # 显示精度（小数点后位数）
unit: 'A'               # 单位
# 模板刻度点集标注
candidate_points:
  - [176, 533] # 刻度点1
  - [176, 495] # 刻度点2
  - [193, 399] # 刻度点3
  - [247, 294] # 刻度点4
  - [321, 222] # 刻度点5
  - [389, 177] # 刻度点6
  - [440, 156]
  - [481, 146]
  - [513, 140]
  - [537, 138]
  - [551, 136]
candidate_points_value: [0, 20, 40, 80, 100, 120, 140, 160, 180, 200]
# 扫描区域设置
scan_zone:
  center_point: [432, 376] # 指针上的一点 作为环形扫描区域的中线点
  radius: 60                # 扫描区域半径
  angle: 15                # 扫描区域扇形角度
