# 图像路径配置
template_path: 'source/1.7/template.jpg'
precision: 0              # 显示精度（小数点后位数）
unit: 'A'               # 单位
# 模板刻度点集标注
candidate_points:
  - [114, 514] # 刻度点1
  - [113, 474] # 刻度点2
  - [143, 356] # 刻度点3
  - [229, 227] # 刻度点4
  - [323, 158] # 刻度点5
  - [392, 129] # 刻度点6
  - [435, 117] # 刻度点7
  - [470, 112] # 刻度点8
  - [491, 110] # 刻度点9
  - [505, 109] # 刻度点10
  - [519, 110] # 刻度点11
candidate_points_value: [0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200]
# 扫描区域设置
scan_zone:
  center_point: [321, 514] # 指针上的一点 作为环形扫描区域的中线点
  radius: 70                # 扫描区域半径
  width: 15                # 指针宽度（方便进行扫描）