# 图像路径配置
template_path: 'source/1.4/template.jpg'
precision: 0              # 显示精度（小数点后位数）
unit: 'mA'               # 单位
# 模板刻度点集标注
candidate_points:
  - [35, 69] # 刻度点1
  - [64, 48] # 刻度点2
  - [97, 36] # 刻度点3
  - [134, 35] # 刻度点4
  - [168, 43] # 刻度点5
  - [198, 62] # 刻度点6
candidate_points_value: [0, 100, 200, 300, 400, 500]
# 扫描区域设置
scan_zone:
  center_point: [120, 44] # 指针上的一点 作为环形扫描区域的中线点
  radius: 7                # 扫描区域半径
  width: 15                # 指针宽度（方便进行扫描）